service: stefanini

app: stefanini
org: haroldobeyerbacellar

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  memorySize: 128
  iamRoleStatements: 
    - Effect: Allow
      Action:
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:us-east-1:529198180535:table/stefanini


functions:
  getEmployee:
    handler: handlers/employee-handler.getEmployee
    events:
      - http: 
          path: employee/{employeeId}
          method: GET
          cors: true
  updateEmployee:
    handler: handlers/employee-handler.updateEmployee
    events:
      - http: 
          path: employee/{employeeId}
          method: PUT
          cors: true
  patchEmployee:
    handler: handlers/employee-handler.patchEmployee
    events:
      - http: 
          path: employee/{employeeId}
          method: PATCH
          cors: true
  deleteEmployee:
    handler: handlers/employee-handler.deleteEmployee
    events:
      - http: 
          path: employee/{employeeId}
          method: DELETE
          cors: true
  insertEmployee:
    handler: handlers/employee-handler.insertEmployee
    events:
      - http: 
          path: employee
          method: POST
          cors: true
  getAllEmployees:
    handler: handlers/employee-handler.getAllEmployees
    events:
      - http: 
          path: employee
          method: GET
          cors: true